# Generated by Django 3.1.7 on 2021-04-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('artist_url', models.URLField()),
                ('tracks_url', models.URLField()),
                ('self_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('albums_url', models.URLField()),
                ('tracks_url', models.URLField()),
                ('self_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField()),
                ('artist_url', models.URLField()),
                ('album_url', models.URLField()),
                ('self_url', models.URLField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_api.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_api.artist'),
        ),
    ]
